### ISSUE TITLE
can not work with node/6.2.2

### ISSUE THREAD

**Issue by onewayxp** [song940/node-escpos#11]
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/oneway/GitLab/2016/MkCRM/batch/node_modules/escpos/node_modules/usb/usb.js:5:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by onewayxp** [comment]
Now works fine with electron 1.3.5 (node 6.3.0)

https://github.com/electron/electron/blob/master/docs-translations/zh-CN/tutorial/using-native-node-modules.md

export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=1.3.5
export npm_config_arch=x64
export npm_config_runtime=electron
HOME=~/.electron-gyp npm install module-name
