### ISSUE TITLE
Error when trying print multiple tickets

### ISSUE THREAD

**Issue by KenWelda** [song940/node-escpos#117]
First tickets is fine, when I want to print the second one following error comes up:
```
// Select the adapter based on your printer type
const escpos    = require('escpos');
//const device  = new escpos.USB();
const device  = new escpos.Network('10.20.2.5');
// const device  = new escpos.Serial('/dev/usb/lp0');
 
const printer = new escpos.Printer(device);
device.open(function(){
        printer
        .font('a')
        .align('ct')
        .style('bu')
        .size(1, 1)
        .text('hello')
        .text('Uw volgnr is:')
        .text('A' + tickets.length)
        .text('')
        .cut()
        .close();
       });
```
```
TypeError: Cannot read property 'on' of null                                                        
	at Network.open (/var/node/ticket/node_modules/escpos/adapter/network.js:28:15)                 
	at /var/node/ticket/app.js:389:14                                                               
	at /var/node/ticket/app.js:619:9                                                                
	at /var/node/ticket/node_modules/mongoose/lib/query.js:3115:18                                  
	at newTickHandler (/var/node/ticket/node_modules/mpromise/lib/promise.js:234:18)                
	at _combinedTickCallback (internal/process/next_tick.js:131:7)                                  
	at process._tickDomainCallback (internal/process/next_tick.js:218:9)   
``` 

when trying this, I can print 2 tickets. after this I'm getting Maximum call stack size exceeded.
```
device.open(function(){
        printer
        .font('a')
        .align('ct')
        .style('bu')
        .size(1, 1)
        .text('Welkom bij Welda')
        .text('Uw volgnr is:')
        .text('A' + tickets.length)
        .text('')
        .cut()
       });
```
```
RangeError: Maximum call stack size exceeded                                                                                
	at Object.getEncoder (/var/node/ticket/node_modules/iconv-lite/lib/index.js:109:19)                                     
	at Object.encode (/var/node/ticket/node_modules/iconv-lite/lib/index.js:18:25)                                          

	at Printer.text (/var/node/ticket/node_modules/escpos/printer.js:113:27)                                                
	at /var/node/ticket/app.js:397:10                                                                                       
	at Socket.device.on (/var/node/ticket/node_modules/escpos/adapter/network.js:29:17)                                     
	at Socket.emit (events.js:164:20)                                                                                       
	at onwriteError (_stream_writable.js:403:12)                                                                            
	at onwrite (_stream_writable.js:431:5)                                                                                  
	at Socket.destroy (internal/streams/destroy.js:12:7)                                                                    
	at Socket._writeGeneric (net.js:732:10)                                                                                 
	at Socket._write (net.js:792:8)                                                                                         
	at doWrite (_stream_writable.js:388:12)                                                                                 
	at writeOrBuffer (_stream_writable.js:374:5)                                                                            
	at Socket.Writable.write (_stream_writable.js:291:11)                                                                   
	at Socket.write (net.js:710:40)                                                                                         
	at Network.write (/var/node/ticket/node_modules/escpos/adapter/network.js:43:15)
```

**Comment by KenWelda** [comment]
Ok I had to define device again:
```
    const device  = new escpos.Network('10.20.2.5');
    const printer = new escpos.Printer(device);
      device.open(function(err){
        printer
        .font('a')
        .align('ct')
        .style('bu')
        .size(1, 1)
        .text('Welkom bij Welda')
        .text('Uw volgnr is:')
        .text('S' + tickets.length)
        .text('')
        .cut()
        .close();
      });
```
