### ISSUE TITLE
Cannot read property 'write' of null

### ISSUE THREAD

**Issue by pholmesp** [song940/node-escpos#156]
Hi, I am trying to develop a API utilizing a POS-8220 thermal printer in Node.js. I followed the instruction and initialized both networkDevice and networkPrinter with the printer's IP address. Unfortunately, I encountered an error which said Cannot read property 'write' of null. Could anybody help? Below are the code snippet and the error. Thanks

Code:
```
router.get('/print', function(req, res, next){
  const networkDevice  = new escpos.Network('10.0.0.122', 9100);
  const networkPrinter = new escpos.Printer(networkDevice);

  networkDevice.open(function(){
    networkPrinter
    .font('a')
    .align('ct')
    .style('bu')
    .size(1, 1)
    .text('The quick brown fox jumps over the lazy dog')
    .text('敏捷的棕色狐狸跳过懒狗')
    .barcode('1234567', 'EAN8')
    .qrimage('https://github.com/song940/node-escpos', function(err){
      this.cut();
      this.close();
    });
  });
    });
```

Error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'write' of null
    at Network.write (/server/node_modules/escpos/adapter/network.js:43:14)
    at Printer.flush (/server/node_modules/escpos/printer.js:568:16)
    at Printer.close (/server/node_modules/escpos/printer.js:592:15)
    at Printer.<anonymous> (/server/routes/index.js:862:12)
    at /server/node_modules/escpos/printer.js:480:26
    at /server/node_modules/get-pixels/node-pixels.js:22:5
    at exports.PNG.<anonymous> (server/node_modules/pngjs/lib/png.js:75:7)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at exports.PNG.emit (events.js:210:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Psychopoulet** [comment]
function(err){
      this.cut();
      this.close();
    }


(err) => {
      this.cut();
      this.close();
    }


??
