### ISSUE TITLE
can not print image by printer.image function

### ISSUE THREAD

**Issue by Debdut** [song940/node-escpos#218]
I tried running the examples in my Macbook Pro 2019, the image.js had the following error:

```
node-escpos/examples/image.js:18
    .image(image, 'd8')
     ^

TypeError: printer.align(...).image(...).image is not a function
    at node-escpos/examples/image.js:18:6
    at Interface.<anonymous> (node-escpos/adapter/usb.js:130:23)
    at Device.<anonymous> (node-escpos/node_modules/usb/usb.js:337:6)
```

**Comment by Psychopoulet** [comment]
'cause "image" is an async method, it does not really return "this"
