### ISSUE TITLE
Can't fetch printer status for Network device

### ISSUE THREAD

**Issue by jamie3** [song940/node-escpos#299]
Using a network printer adapter and trying to fetch the status of the printer and no luck.

```
"escpos": "~3.0.0-alpha.4",
"escpos-network": "~3.0.0-alpha.2"
```

Here is my code creating the printer:

```
        const device = new escpos.Network(printerIpAddress);
        const printer = new escpos.Printer(device);
```

Here is the code I am executing from the example documentation:

```
            printer
              .getStatuses((status => {
                console.log(status.toJSON());
              })
              .close();
```

This fails:

```
TypeError: this.adapter.read is not a function
    at Printer.getStatuses (c:\dev\code\rafflebox\barrel-printer\node_modules\escpos\index.js:894:16)
    at c:\dev\code\rafflebox\barrel-printer\src\main.ts:98:16
    at Socket.<anonymous> (c:\dev\code\rafflebox\barrel-printer\node_modules\escpos-network\index.js:34:17)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1127:10)
```

Looking at the code it appears Network printer does not have `read` function code as per the example with Serial device.

https://github.com/song940/node-escpos/blob/v3/packages/network/index.js
https://github.com/song940/node-escpos/blob/v3/packages/serialport/index.js

```
Serial.prototype.read = function(callback) {
  this.device.on('data', function(data) {
    callback(data);
  });
  return this;
};
```

**Comment by lsongdev** [comment]
escpos-network@3.0.0-alpha.5
