### ISSUE TITLE
Cannot read properties of null (reading 'on')

### ISSUE THREAD

**Issue by mattyx97** [song940/node-escpos#386]
Hi, I have a problem, when I start the server with this code
```
`'use strict';
const path = require('path')
const escpos = require('escpos')
escpos.Network = require('escpos-network');

const device = new escpos.Network('192.168.1.200', 9100);
const options = { encoding: "GB18030" }
const printer = new escpos.Printer(device)






var bodyParser = require('body-parser')
var app = require('express')()
var http = require('http').Server(app)
var cors = require('cors')
app.use(cors())
app.use(bodyParser.json())

const port = 4000;

app.post('/print', (req, res) => {
  res.json(
    { status: 'success' }
  )
  console.log(req.body)
  print(req.body.text)
});

http.listen(port, () => {
  console.log(`Printer: http://localhost:${port}`);
});

const print = (text) => {
  device.open(function () {
    printer
      .font('a')
      .align('ct')
      .style('bu')
      .size(3, 3)
      .text(text)
      .cut()
      .close();
  });
}
`
```

I can only do one print after which if I try to do another print I have this problem

`TypeError: Cannot read properties of null (reading 'on')
    at Network.open (C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\escpos-network\index.js:30:15)
    at print (C:\Users\matti\Downloads\node-escpos-3\examples\web\server.js:37:10)
    at C:\Users\matti\Downloads\node-escpos-3\examples\web\server.js:29:3
    at Layer.handle [as handle_request] (C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\express\lib\router\index.js:286:22
    at Function.process_params (C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\express\lib\router\index.js:348:12)
    at next (C:\Users\matti\Downloads\node-escpos-3\examples\web\node_modules\express\lib\router\index.js:280:10)`

Please could you help me solve this problem, I can't seem to figure it out!

**Comment by Epizefiri** [comment]
HI @mattyx97,
did you ever solved?
