### ISSUE TITLE
Print without qrimage

### ISSUE THREAD

**Issue by emrealparslan93** [song940/node-escpos#47]
Hello, 
I'm trying to print a text without qrimage. But sometimes, it gives me following error: 

> 
    /Users/emrealparslan/Projects/print-server/node_modules/usb/usb.js:43
    	this.__close()
    	     ^

    Error: Can't close device with a pending request
        at Error (native)
        at Device.usb.Device.close (/Users/emrealparslan/Projects/print-server/node_modules/usb/usb.js:43:7)
        at USB.close (/Users/emrealparslan/Projects/print-server/node_modules/escpos/adapter/usb.js:141:15)
        at OutEndpoint.<anonymous> (/Users/emrealparslan/Projects/print-server/node_modules/escpos/printer.js:430:18)
        at Transfer.callback (/Users/emrealparslan/Projects/print-server/node_modules/usb/usb.js:362:14)

Here is my print function: 

> 
    function print(p, text) {
    const escpos = require('escpos');

    // Select the adapter based on your printer type
    const device = new escpos.USB(p.vendorId, p.productId);
    const printer = new escpos.Printer(device);
    device.open(function() {
        printer
            .font('a')
            .style('bu')
            .align('ct')
            .size(1, 1)
            .text(text);
        printer.cut();
        printer.close();
    });
    };

Is there a way printing without 'qrimage'. Because it seems only 'qrimage' has a function to cut&close.

**Comment by adamxp12** [comment]
You seem to be able to do just .cut() and .close() instead of doing printer.cut() and printer.close()

should really have that in the examples
